apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: service-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: service-demo
    spec:
      containers:
      - name: service1
        image: asia-south1-docker.pkg.dev/cision-ness/ness-docker-repo/service1:v300
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8081
          protocol: TCP
